_ = lambda text: text
STRING_TAGS = [
    'p',
    'strong',
    'emphasis',
    'strikethrough',
    'sub',
    'sup',
    'code',
]


GENRES = {
    'sf_history': _('alternative history'), 'sf_action': _('Combat fiction'),
    'sf_epic': _('Epic fiction'), 'sf_heroic': _('Heroic fiction'),
    'sf_detective': _('Detective fiction'), 'sf_cyberpunk': _('Cyberpunk'),
    'sf_space': _('Space fiction'),
    'sf_social': _('Socio-psychological fiction'),
    'sf_horror': _('Horror and Mystery'), 'sf_humor': _('Humorous fiction'),
    'sf_fantasy': _('Fantasy'), 'sf': _('Science fiction'),
    'det_classic': _('Classic detective'), 'det_police': _('Police detective'),
    'det_action': _('Action'), 'det_irony': _('Ironic detective'),
    'det_history': _('Historical detective'),
    'det_espionage': _('Spy detective'),
    'det_crime': _('Crime detective'),
    'det_political': _('Political detective'),
    'det_maniac': _('Maniacs'), 'det_hard': _('Cool detective'),
    'thriller': _('Thriller'), 'detective': _('Detective'),
    'prose_classic': _('Classical prose'),
    'prose_history': _('Historical prose'),
    'prose_contemporary': _('Contemporary prose'),
    'prose_counter': _('Counterculture'),
    'prose_rus_classic': _('Russian classical prose'),
    'prose_su_classics': _('Soviet classical prose'),
    'love_contemporary': _('Modern romance novels'),
    'love_history': _('Historical romance novels'),
    'love_detective': _('Action-packed romance novels'),
    'love_short': _('Short romance novels'),
    'love_erotica': _('Erotic'), 'adv_western': _('Western'),
    'adv_history': _('Historical adventures'),
    'adv_indian': _('Adventures about Indians'),
    'adv_maritime': _('Nautical adventures'),
    'adv_geo': _('Travel and geography'),
    'adv_animal': _('Nature and animals'), 'adventure': _('Adventures'),
    'child_tale': _('Story'), 'child_verse': _('Children\'s poems'),
    'child_prose': _('Children\'s prose'),
    'child_sf': _('Children\'s fiction'),
    'child_det': _('Children\'s action-packed'),
    'child_adv': _('Children\'s adventures'),
    'child_education': _('Children\'s educational literature'),
    'children': _('Children\'s literature'),
    'poetry': _('Poetry'), 'dramaturgy': _('Dramaturgy'),
    'antique_ant': _('Ancient literature'),
    'antique_european': _('European ancient literature'),
    'antique_russian': _('Old Russian literature'),
    'antique_east': _('Ancient oriental literature'),
    'antique_myths': _('Myths. Legends. Epos'),
    'antique': _('Ancient literature'),
    'sci_history': _('History'), 'sci_psychology': _('Psychology'),
    'sci_culture': _('Culturology'), 'sci_religion': _('Religious Studies'),
    'sci_philosophy': _('Philosophy'), 'sci_politics': _('Politics'),
    'sci_business': _('Business literature'), 'sci_juris': _('Jurisprudence'),
    'sci_linguistic': _('Linguistics'), 'sci_medicine': _('Medicine'),
    'sci_phys': _('Physics'), 'sci_math': _('Mathematics'),
    'sci_chem': _('Chemistry'), 'sci_biology': _('Biology'),
    'sci_tech': _('Technical science'), 'science': _('Scientific literature'),
    'comp_www': _('Internet'), 'comp_programming': _('Programming'),
    'comp_hard': _('Computer hardware'), 'comp_soft': _('Programs'),
    'comp_db': _('Database'), 'comp_osnet': _('OS and Networks'),
    'computers': _('Near-computer literature'),
    'ref_encyc': _('Encyclopedias'),
    'ref_dict': _('Dictionaries'), 'ref_ref': _('Directories'),
    'ref_guide': _('Manuals'), 'reference': _('Reference literature'),
    'nonf_biography': _('Biographies and Memoirs'),
    'nonf_publicism': _('Journalism'),
    'nonf_criticism': _('Criticism'), 'design': _('Art & Design'),
    'nonfiction': _('Documental literature'), 'religion_rel': _('Religion'),
    'religion_esoterics': _('Esoterics'),
    'religion_self': _('Self improvement'),
    'religion': _('Religious literature'), 'humor_anecdote': _('Jokes'),
    'humor_prose': _('Humorous prose'), 'humor_verse': _('Humorous poems'),
    'humor': _('Humor'), 'home_cooking': _('Cooking'),
    'home_pets': _('Pets'), 'home_crafts': _('Hobbies and crafts'),
    'home_entertain': _('Entertainment'), 'home_health': _('Health'),
    'home_garden': _('Garden'), 'home_diy': _('Do it yourself'),
    'home_sport': _('Sport'), 'home_sex': _('Erotic, Sex'),
    'home': _('Housekeeping')
}

MESSAGES = {
    'element_not_found': _('Element {element_name} not found'),
    'attribute_not_found': _('Attribute {attribute_name} not found'),
    'translator': _('Translator'),
    'translators': _('Translators'),
    'language': _('Language'),
    'original_language': _('Original language'),
    'date': _('Date of writing'),
    'annotation': _('Annotation'),
    'original_metadata': _('Original metadata'),
    'edition_information': _('Edition information'),
    'contents': _('Table of contents'),
}
